Revert "Update to ghc-9.6.4"
The static build failed with:
   error: builder for '/nix/store/zvgn6rpry874jgf9yvm8kp44pb3k0gh9-podenv-0.5.0.drv' failed with exit code 1;
       last 25 log lines:
       > /nix/store/0wk2xdfq01f35k8a0mch7g3l5csdxygv-binutils-2.41/bin/ld: (.text+0x179): undefined reference to `gelf_xlatetom'
       > /nix/store/0wk2xdfq01f35k8a0mch7g3l5csdxygv-binutils-2.41/bin/ld: /nix/store/5kgfm9zk9wgzm9p19j1sihd9ir85y30q-elfutils-0.190/lib/libdw.a(dwarf_begin.o): in function `dwarf_begin':

This reverts commit c8d6737eb6b4d4cc0d2cf23505cab66b1468d59e.