.cabal build-depends: dhall >= 1.34
With dhall-1.32 (Fedora 34) one gets:

src/Podenv/Dhall.hs:39:3: error:
    * Record update is ambiguous, and requires a type signature
    * In the expression: a {Podenv.Dhall.image_volumes = x_amBJ}
      In the first argument of `fmap', namely
        `(\ x_amBJ -> a {Podenv.Dhall.image_volumes = x_amBJ})'
      In the expression:
        ((\ x_amBJ -> a {Podenv.Dhall.image_volumes = x_amBJ})
           `fmap` f (Podenv.Dhall.image_volumes a))
   |
39 | $(makeLensesBy (\n -> Just $ "cb" <> [toUpper $ head n] <> tail n) ''ContainerBuild)
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^